### PR TITLE
Use API to get_user_str_from_profile

### LINKED ISSUE #320: [BUG] AttributeError: 'NoneType' object has no attribute 'text'
**Describe the bug**
Seems that coomer.su links are not downloading for me. I tried removing all files and reinstalling but still getting the error with coomer.su sites. 

**To Help Reproduce**
Steps to help reproduce the behavior:
Have a coomer link in your URLs.txt
Select the profile and attempt to download the coomer.su profile.
The scrape fails for me with the error in logs 
```
ERROR    Scrape Failed: https://coomer.su/onlyfans/user/bunniepremium ('NoneType' object has no attribute 'text')     
```

**Screenshots**

**Setup Information**
 - OS: Windows 11 Python 3.11.6
 - Cyberdrop Downloader Version # 5.7.2

**Downloader.log file**

[downloader.log](https://github.com/user-attachments/files/17912592/downloader.log)

**Additional context**

### PR DESCRIPTION
**Pull request by electricfish1**
fixes #320

### CODE REVIEW

**Comment by datawhores** [comment]
@jbsparrow is working on a fix based on the 5.7.2 tag
The master branch has some bugs to fix, so were not releasing any official releases based on that at the moment

File: cyberdrop_dl/scraper/crawlers/coomer_crawler.py [hunk 1]
```diff
@@ -217,10 +217,12 @@ async def get_user_str_from_post(self, scrape_item: ScrapeItem) -> str:
         return soup.select_one("a[class=post__user-name]").text
 
     async def get_user_str_from_profile(self, scrape_item: ScrapeItem) -> str:
-        """Gets the user string from a scrape item."""
+        """Gets the user string from a scrape item"""
+        service, user = await self.get_service_and_user(scrape_item)
```
Comment (lerroynick) [inline cyberdrop_dl/scraper/crawlers/coomer_crawler.py:221]: remove await. await cant return tuples. 
Then it works.

**Comment by jbsparrow** [comment]
#326 Fixes this & Kemono. Took a bit long I got distracted 😅
