### ISSUE TITLE
[BUG] 6.10.0 crashes with `ImportError: cannot import name 'MethodType' from 'types'` at startup

### ISSUE THREAD

**Issue by baccccccc** [jbsparrow/CyberDropDownloader#1029]
### I have taken steps to troubleshoot my issue first

- [x] I'm using the latest version of `cyberdrop-dl-patched`
- [x] I’ve read the wiki and my issue isn’t already covered.
- [x] I understand this is open source software provided for free and that I might not receive a timely response.
- [x] I’ve checked existing issues to avoid creating a duplicate.
- [ ] A similar issue was previously marked as `completed` and the [changelog](https://github.com/jbsparrow/CyberDropDownloader/blob/dev/CHANGELOG.md) says it was implemented, but I'm confident the bug still exists
- [ ] I am willing to submit a pull request with the fix. *(Assign this issue to me.)*

### Describe the bug

That was not the case with 6.9.1 but after upgrade to 6.10.0, launching CDL crashes with
```
Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\cyberdrop_dl\main.py", line 3, in <module>
    from cyberdrop_dl import env
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\cyberdrop_dl\__init__.py", line 1, in <module>
    import importlib.metadata
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\Lib\importlib\metadata\__init__.py", line 4, in <module>
    import re
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\Lib\re\__init__.py", line 125, in <module>
    import enum
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\Lib\enum.py", line 4, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\cyberdrop_dl\types.py", line 12, in <module>
    from pathlib import Path
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\Lib\pathlib\__init__.py", line 8, in <module>
    from ._abc import *
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\Lib\pathlib\_abc.py", line 15, in <module>
    from glob import _Globber, _no_recurse_symlinks
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\Lib\glob.py", line 3, in <module>
    import contextlib
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\Lib\contextlib.py", line 8, in <module>
    from types import MethodType, GenericAlias
ImportError: cannot import name 'MethodType' from 'types' (consider renaming 'C:\\Users\\<username>\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\cyberdrop_dl\\types.py' since it has the same name as the standard library module named 'types' and prevents importing that standard library module)
```

### Steps to help reproduce the behavior

see above

### Relevant logs

n/a

### Operating system/environment

Windows 11, version 24H2

### Python Version

3.13.3

### Cyberdrop-DL version

6.10.0

**Comment by baccccccc** [comment]
ok I downloaded a snapshot of `dev` branch once #1039 got merged and I now get a different, yet similar error.

```
Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\cyberdrop_dl\main.py", line 3, in <module>
    from cyberdrop_dl import env
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\cyberdrop_dl\__init__.py", line 1, in <module>
    import importlib.metadata
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\Lib\importlib\metadata\__init__.py", line 4, in <module>
    import re
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\Lib\re\__init__.py", line 125, in <module>
    import enum
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\Lib\enum.py", line 4, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\cyberdrop_dl\types.py", line 11, in <module>
    from typing import TYPE_CHECKING, Any, Literal, NewType, ParamSpec, TypeAlias, TypeVar, overload
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.13_3.13.1008.0_x64__qbz5n2kfra8p0\Lib\typing.py", line 30, in <module>
    from types import WrapperDescriptorType, MethodWrapperType, MethodDescriptorType, GenericAlias
ImportError: cannot import name 'WrapperDescriptorType' from 'types' (consider renaming 'C:\\Users\\<username>\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python313\\site-packages\\cyberdrop_dl\\types.py' since it has the same name as the standard library module named 'types' and prevents importing that standard library module)
```
