### ISSUE TITLE
[BUG] Crashing during a run

### ISSUE THREAD

**Issue by bewbylover** [jbsparrow/CyberDropDownloader#578]
### I have taken steps to troubleshoot my issue first

- [x] I'm using the latest version of `cyberdrop-dl-patched`
- [x] I’ve read the wiki and my issue isn’t already covered.
- [x] I’ve checked existing issues to ensure this hasn’t been reported already.

### Describe the bug

Run the application with a list of forum URLs, wait and get the following error on the prompt:
An error occurred, please report this to the developer with your logs file:
  
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/aiosqlite/core.py", line 109, in run
    get_loop(future).call_soon_threadsafe(set_result, future, result)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 807, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 520, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/aiosqlite/core.py", line 117, in run
    get_loop(future).call_soon_threadsafe(set_exception, future, e)
  File "/usr/lib/python3.11/asyncio/base_events.py", line 807, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.11/asyncio/base_events.py", line 520, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

^CTraceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/cyberdrop_dl/managers/manager.py", line 249, in close
    await self.cache_manager.close()
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/cyberdrop_dl/managers/cache_manager.py", line 85, in close
    await self.request_cache.close()
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/aiohttp_client_cache/backends/base.py", line 270, in close
    await self.redirects.close()
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/aiohttp_client_cache/backends/sqlite.py", line 159, in close
    await self._connection.close()
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/aiosqlite/core.py", line 171, in close
    await self._execute(self._conn.close)
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/bin/cyberdrop-dl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/cyberdrop_dl/main.py", line 259, in main
    return actual_main()
           ^^^^^^^^^^^^^
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/cyberdrop_dl/main.py", line 275, in actual_main
    asyncio.run(manager.close())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt
Could not close SQLite connection thread
Traceback (most recent call last):
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/aiohttp_client_cache/backends/sqlite.py", line 125, in __del__
    self._connection._stop_running()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Connection' object has no attribute '_stop_running'

### Desired result

Application will run without crashing

### Steps to help reproduce the behavior

Run the application with a list of forum URLs, wait and get the following error on the prompt

### Relevant logs

[downloader.zip](https://github.com/user-attachments/files/18716363/downloader.zip)

### Operating system/environment

Ubuntu 20.04.6 LTS

### Python Version

3.8.10

### Cyberdrop-DL version

6.4.0

**Comment by NTFSvolume** [comment]
- This is caused by #389

**Comment by bewbylover** [comment]
Is there any way to recover?

**Comment by NTFSvolume** [comment]
There's no fix for this yet

**Comment by bewbylover** [comment]
The try catch wrapper might be a good mitigation until the long term fix is available.
